spring.application.name=Park entry ticket

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

razorpay.api.key=${RAZORPAY_KEY}
razorpay.api.secret=${RAZORPAY_SECRET}

jwt.secret=${JWT_SECRET}